/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.lcs.Explo;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text=0x7f010000;
    }
    public static final class drawable {
        public static final int audio=0x7f020000;
        public static final int default_icon=0x7f020001;
        public static final int dossier=0x7f020002;
        public static final int html=0x7f020003;
        public static final int image=0x7f020004;
        public static final int inconnue=0x7f020005;
        public static final int retour=0x7f020006;
        public static final int texte=0x7f020007;
        public static final int video=0x7f020008;
    }
    public static final class id {
        public static final int grid=0x7f050000;
    }
    public static final class layout {
        public static final int princ_xml=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a styleFichier.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #styleFichier_text com.lcs.Explo:text}</code></td><td></td></tr>
           </table>
           @see #styleFichier_text
         */
        public static final int[] styleFichier = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.lcs.Explo.R.attr#text}
          attribute's value can be found in the {@link #styleFichier} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lcs.Explo:text
        */
        public static final int styleFichier_text = 0;
    };
}
